# https://pnpm.io/supply-chain-security
# https://pnpm.io/settings#managepackagemanagerversions
# https://pnpm.io/installation#using-corepack

engineStrict: true

ignoredBuiltDependencies:
  - esbuild

managePackageManagerVersions: true

minimumReleaseAge: 40320

minimumReleaseAgeExclude:
  - backing-tracks-isomorphic

packageManagerStrictVersion: true

preferFrozenLockfile: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 80640

blockExoticSubdeps: true